Add reviews
ushniihk/java-filmorate pull request #14
Opened 2022-07-24 18:55 UTC by 3e54Ni7HTXo3Ds

2022-07-24 19:01 UTC, ushniihk commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +        if (count <= 0) throw new IncorrectParameterException("Bad count");
Проверки давай в сервис перенесем

2022-07-24 19:13 UTC, ushniihk commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +            review.get().createReviewLike(user.get().getId());
user.get().getId() можно заменить на userId который в параметры передавали?

2022-07-24 19:14 UTC, ushniihk commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +            review.get().createReviewDislike(user.get().getId());
user.get().getId() == userId
?

2022-07-24 19:14 UTC, ushniihk commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +            review.get().deleteReviewLike(user.get().getId());
user.get().getId() == userId
?

2022-07-24 19:20 UTC, ushniihk commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/ReviewDbStorage.java
> +    Integer useful(Integer id) {
модификатор доступа private потерялся

2022-07-24 19:22 UTC, ushniihk commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/ReviewDbStorage.java
> +        //   String sqlQuery = "update REVIEW_LIKE set LIKE_TYPE = ? where REVIEW_ID = ? and USER_ID=?";
комментарии удали пожалуйста

2022-07-25 06:20 UTC, 3e54Ni7HTXo3Ds commented
Закоммитил фикс

2022-07-25 09:18 UTC, ushniihk approved these changes

2022-07-25 09:36 UTC, tonychem requested changes
Очень круто, что получилось реализовать такой большой функционал. 
Почти все мои замечания - стилевые. КМК, лучше убрать магические числа Integer value = 1 или -1, и скрыть их функционал за енамом.

2022-07-25 09:36 UTC, tonychem commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    public void createReviewLike(Integer userId) {
Думаю стоит просто повесить @AllArgsConstructor, чтобы было однотипно с другими моделями

2022-07-25 09:36 UTC, tonychem commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +            throw new NotFoundParameterException("Bad id or content");
Этот фрагмент повторяется в двух методах - createReview и updateReview, думаю стоит сделать private boolean checkRawReview (Review review) метод в этом сервисе и делегировать ему все.

2022-07-25 09:36 UTC, tonychem commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +            throw new NotFoundParameterException("Bad id or content");
тоже в отдельный метод

2022-07-25 09:36 UTC, tonychem commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        Integer value = -1;
Появление магических чисел в коде - bad practice; думаю стоит просто создать енам: 
```java
enum Value {
    LIKE(1), DISLIKE(-1);

    private int dbView;

    Value(int dbView) {
        this.view = view;
    }

    public int getDbView() {
        return view;
    }
}


```

2022-07-25 09:36 UTC, tonychem commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +            reviewStorage.createReviewLikeDislike(reviewId, userId, value);
а здесь будет
```java
reviewStorage.createReviewLikeDislike(reviewId, userId, Value.DISLIKE);
```

2022-07-25 09:36 UTC, tonychem commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/ReviewDbStorage.java
> +
сюда @RequiredArgsConstructor для последовательности

2022-07-25 09:36 UTC, tonychem commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/ReviewDbStorage.java
> +        } else return 0;
Такого лучше избегать, чтобы ненароком не словить SQL Injection, просто :
```java
 String sql = "SELECT SUM (LIKE_TYPE) from REVIEW_LIKE Where REVIEW_ID = ?";
 Integer useful = jdbcTemplate.queryForObject(sql, Integer.class, id);
```

2022-07-25 14:41 UTC, 3e54Ni7HTXo3Ds commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    public void createReviewLike(Integer userId) {
Там уже есть @Data,  @AllArgsConstructor не встретил в других моделях

2022-07-25 14:42 UTC, 3e54Ni7HTXo3Ds commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/ReviewDbStorage.java
> +        } else return 0;
Окей, делал так сразу, почему-то не сработало, сейчас ок

2022-07-25 14:44 UTC, 3e54Ni7HTXo3Ds commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/ReviewDbStorage.java
> +
Ок

2022-07-25 14:59 UTC, 3e54Ni7HTXo3Ds commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        Integer value = -1;
Ок

2022-07-25 14:59 UTC, 3e54Ni7HTXo3Ds commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +            reviewStorage.createReviewLikeDislike(reviewId, userId, value);
Ок

2022-07-25 15:18 UTC, 3e54Ni7HTXo3Ds commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +            throw new NotFoundParameterException("Bad id or content");
Ок

2022-07-25 15:18 UTC, 3e54Ni7HTXo3Ds commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +            throw new NotFoundParameterException("Bad id or content");
Ок

2022-07-25 17:24 UTC, tonychem approved these changes

2022-07-25 17:48 UTC, merged