Develop
ushniihk/java-filmorate pull request #16
Opened 2022-07-26 18:32 UTC by ushniihk

2022-07-27 05:26 UTC, EugeneLenkevich requested changes
Привет,  Александр, спасибо за PR

Ребята молодцы, все в целом очень здорово :)
Я постарался отметить самые важные моменты, которые можно улучшить, посмотри комментарии, пожалуйста :)

2022-07-27 05:26 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (userStorage.getUsersAndLikes().get(id).size() == 0 || userStorage.getUserIdWithCommonLikes(id) == -1 ||
А не лучше ли в сторедже создать соответствующий поисковый метод и всю логику поиска поместить в него? 
Так мы спрячем детали реализации :)
что то вроде 
hasLikes
hasRecommendedFilms

2022-07-27 05:26 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/DirectorDbStorage.java
> +    public void addDirector(Integer ID, Integer filmID) {
В качестве параметров метода лучше мне кажется передавать непосредственно Director и Film, а уже в сам запрос подставлять их id. Так будет проще и надежней :)

public void addDirector(Director director, Film film) {...

Ну и название метода не отображает то что он делает, метод же по своей сути связывает две сущности, а не добавляет :)

link(...)
attach(...)

2022-07-27 05:26 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    public Collection<Film> findFilmsByDirector(Integer directorID, String sortBy) throws NotFoundParameterException {
Опять таки, а что если метод сделать вот таким, будет ли он более кратким без потери смысла :)

Collection<Film> find(Director director, String sortBy)

Аналогично по другим методам, если интерфейс называется _Film_Storage, то логично что он работает с сущностями Film, соответственно в методах это слово дублировать не надо, а то масло-масляное :)

2022-07-27 05:26 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/ReviewDbStorage.java
> +        if (findAll().contains(review)) {
findAll()

Здесь вытаскиваются все записи из БД, а потом по ним идет поиск нужного id. Однако, возможна ситуация, когда записей в таблице пару сотен миллиардов :)
Хотелось бы перенести проверку на существование переложить на уровень БД =)

https://stackoverflow.com/questions/7471625/fastest-check-if-row-exists-in-postgresql

2022-07-27 05:26 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        for (User user : findAll()) {
Опять таки, зачем все записи из таблицы вытаскивать, никакой ОЗУ не хватит, не лучше ли сделать метод который будет искать соответствующие записи для одного/нескольких пользователей? :)

2022-07-27 09:24 UTC, ushniihk commented on src/main/java/ru/yandex/practicum/filmorate/model/Director.java
> +        super();
ок

2022-07-27 09:39 UTC, ushniihk commented on src/main/java/ru/yandex/practicum/filmorate/model/Event.java
> +    public Event(Long timestamp, Integer userId, Integer eventId, Long entityId, String eventType, String operation) {
ok

2022-07-27 09:47 UTC, ushniihk commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (userStorage.getUsersAndLikes().get(id).size() == 0 || userStorage.getUserIdWithCommonLikes(id) == -1 ||
ok

2022-07-27 16:30 UTC, ushniihk commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/DirectorDbStorage.java
> +    public void addDirector(Integer ID, Integer filmID) {
Это тоже история про сокрытие деталей реализации?

2022-07-27 17:09 UTC, ushniihk commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    public Collection<Film> findFilmsByDirector(Integer directorID, String sortBy) throws NotFoundParameterException {
поправил нейминги по всему коду

2022-07-27 19:36 UTC, ushniihk commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/ReviewDbStorage.java
> +        if (findAll().contains(review)) {
ok

2022-07-27 19:41 UTC, ushniihk commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        for (User user : findAll()) {
немного улучшил ситуацию на мой взгляд)

2022-07-27 19:52 UTC, ushniihk commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    public Collection<Film> findFilmsByDirector(Integer directorID, String sortBy) throws NotFoundParameterException {
Collection find(Director director, String sortBy)
 в этот метод чтоб передать Director его нужно специально создавать в сервисе, не кастыль ли это? и имеет ли это смысл дергать лишний раз метод по созданию сущности ради сокрытия реализации?

2022-07-28 03:25 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/DirectorDbStorage.java
> +    public void addDirector(Integer ID, Integer filmID) {
Не, это про читаемость :)

2022-07-28 03:40 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        for (User user : findAll()) {
В общем, чем больше работы с данными перенесено на уровень БД, тем лучше. БД может оперировать свободно гигабайтами данных, наше же приложение захлебнется на небольшом объеме. Плюс не надо забывать, что у нас может быть много пользователей, а временами может набежать очень много, видел же не раз как некоторые сервисы временами отваливаются, особенно во время каких то событий, когда народ начинает массово ломится на какой то сайт :)

2022-07-28 03:42 UTC, EugeneLenkevich approved these changes
Все супер, спасибо!

2022-07-28 04:48 UTC, merged