Add marks
ushniihk/java-filmorate pull request #17
Opened 2022-07-30 10:24 UTC by ushniihk

2022-07-30 10:58 UTC, AlNedorezov commented on pom.xml
> +			<artifactId>springdoc-openapi-ui</artifactId>
здорово что используете

2022-07-30 11:03 UTC, AlNedorezov requested changes
Не увидел реализацию того что в рекомендациях ищутся пользователи с похожими оценками по одним и тем-же фильмам.

Изменения не покрыты тестами, нужно написать свои postman тесты на реализованный функционал и приложить их в репозиторий

2022-07-31 11:05 UTC, AlNedorezov commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        double count = 10;
В целом весь алгоритм поиска можно было в sql запрос тут реализовать

2022-07-31 11:06 UTC, AlNedorezov commented
коллекция с тестами последнего задания https://www.postman.com/collections/1dc602f0612c12f6e43e

2022-07-31 11:07 UTC, AlNedorezov commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +    private int fuu(int filmid, int userID, int id) throws NotFoundParameterException {
название непонятное, так лучше не делать. Нужно или называть методы так чтобы было понятно по названию что они делают (предпочтительно), или писать JavaDoc

2022-07-31 11:10 UTC, AlNedorezov commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        String sql = "SELECT FILM_ID FROM FILM_LIKES WHERE USER_ID = ?";
А где теперь выполнятся условие что нужно рекомендовать фильмы только с "пложительной" оценкой?

2022-07-31 11:31 UTC, ushniihk commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        String sql = "SELECT FILM_ID FROM FILM_LIKES WHERE USER_ID = ?";
private Collection<Integer> getBadLikedFilms(Integer id) {
        String sql = "SELECT FILM_ID FROM FILM_LIKES WHERE USER_ID = ? AND MARK < 6";
        return  jdbcTemplate.query(sql, (rs, rowNum) -> rs.getInt("FILM_ID"), id);
    }
    вот тут

2022-07-31 11:34 UTC, ushniihk commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +    private int fuu(int filmid, int userID, int id) throws NotFoundParameterException {
Согласен, поспешил, исправим)

2022-07-31 11:38 UTC, ushniihk commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        double count = 10;
уверен что так можно, но пока смог только на таком уровне реализовать. Мой способ будет совсем не продуктивен в реальной жизни?

2022-07-31 13:44 UTC, AlNedorezov commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        String sql = "SELECT FILM_ID FROM FILM_LIKES WHERE USER_ID = ?";
Понял, спасибо

2022-07-31 13:47 UTC, AlNedorezov approved these changes
В целом требования выполнены.
Для работы с большими системами нужно по хорошему переписать так чтобы получение рекоментаций выполнялось одним sql запросом, без логики в приложении, т.к. при увеличении размеров фильмов будет замедляться логика работы и будет расходоваться память приложения на хранения всё более больших коллекций

2022-07-31 16:16 UTC, merged