feat: add FilmStorage and UserStorage implementation, Create InMemory…
ushniihk/java-filmorate pull request #3
Opened 2022-06-12 19:13 UTC by ushniihk

…FilmStorage and InMemoryUserStorage classes, Create UserService class, Create FilmService class, Add Full REST, add new tests.

2022-06-12 19:26 UTC, eugene-lenkevich requested changes
Привет, Александр, спасибо за PR

В целом все супер :)
Есть совсем небольшие замечания, посмотри комментарии ниже, пожалуйста

2022-06-12 19:26 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    FilmStorage filmStorage;
Контроллер все же пусть зависит только от сервиса, а вот сервис зависит от хранилища (storage), тогда у нас будут слои: уровень контроллера, уровень бизнес-логики и уровень хранилища данных. Иначе у нас контроллер оказывается жестко связанным с деталями реализации нижележащих слоев. 
В общем, давай связь с storage отсюда уберем и будем к нему обращаться через методы сервиса  :)

2022-06-12 19:26 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +                .forEach(i -> list.add(users.get(i)));
Можно улучшить стрим примерно так, но надо проверить :)
...
.map(users::get)
.forEach(list::add);

2022-06-13 18:10 UTC, ushniihk commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    FilmStorage filmStorage;
тут вроде понял Controller <- Service <- Storage

2022-06-13 18:13 UTC, ushniihk commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +                .forEach(i -> list.add(users.get(i)));
а вот тут не понял вообще)) не понял как твой вариант применим в этом случае, я может просто слабоват в стримах и не вижу этой реализации, но если сможешь пояснить ход мыслей или как то навести на раздумья

2022-06-13 18:31 UTC, eugene-lenkevich approved these changes
Все супер, спасибо!

2022-06-26 19:03 UTC, merged