feature: add DB, add DAO, modify User and Film, add entyties MPA and …
ushniihk/java-filmorate pull request #5
Opened 2022-07-13 20:01 UTC by ushniihk

…Genres

2022-07-14 16:37 UTC, eugene-lenkevich requested changes
Привет, Александр, спасибо за PR

В целом все супер :)
Есть совсем небольшие замечания, посмотри комментарии ниже, пожалуйста

2022-07-14 17:01 UTC, ushniihk commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (filmStorage.getFilm(id).isPresent() && userStorage.getUser(userId).isPresent()) {
Привет, тут не один и тот же запрос, мы проверяем фильм и юзера на то что они не NULL а потом дергает 1 фильм и одного юзера.

2022-07-14 18:36 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (filmStorage.getFilm(id).isPresent() && userStorage.getUser(userId).isPresent()) {
![image](https://user-images.githubusercontent.com/109306643/179057060-79cb74c2-7f7f-44c0-90fa-e4aa2f0d3435.png)

Тут два запроса, на каждый он возвращает Optional :)

2022-07-14 18:37 UTC, EugeneLenkevich requested changes
Добавил комментарий, просто в переменную вынеси, не надо два раза дергать  :)

2022-07-14 18:56 UTC, ushniihk commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (filmStorage.getFilm(id).isPresent() && userStorage.getUser(userId).isPresent()) {
оке, про переменную понял

2022-07-15 00:33 UTC, EugeneLenkevich approved these changes
Все супер, спасибо!

2022-07-18 18:47 UTC, merged